### ISSUE TITLE
feat: uris with flakes in sub-directory

### ISSUE THREAD

**Issue by 573** [cafkafk/rime#65]
I would like to use uris of the form `github:owner/repo/?dir=*` to have inputs such as the following in my flake:
```nix
    rust-dev-template = {
      url = "github:the-nix-way/dev-templates/?dir=rust";
    };
```

**Comment by 573** [comment]
Probably for me this would be confusing why posting this upstream, so reason is: he adopted flakehub uris [recently](https://github.com/the-nix-way/dev-templates/compare/v0.1.0...v0.1.1).

**Comment by 573** [comment]
Just now saw that I can just
```
nix develop http://rime.cx/v1/github.com/the-nix-way/dev-templates/branch/main.tar.gz?dir=rust --impure
```
So nothing to do with rime.

Thanks for this great project !

**Comment by cafkafk** [comment]
> Thanks for this great project !

Glad you like it!
